appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: v8BsecCau/RREenksC5l+V8Qe2kzWKWUARBjW/MgqFTU16GUSsUisN4dWxWaUs8iKN3m0THoflcJRlFp+htbljtEvrPifMzt3K+Uf5priQ32nsZ2JLEA4p7pyG7/EOhc10RP13l2AbEtPCxs5LSs+od1D+1hKKZ4Cvur2zlf/Lnp9RymQ/y/vfp868G+2FxSe0CFBs7g04sEobOHUmfx67h+oIosSeYveaujejgLSiZohn53OLGqf36PxZRn9AnHbUCu+2V71DHGO8fzmeJlcvaC8GRdDL4iHRza9MeTJGaouDx2qkDZy8lzDKZoVoS7cLfxZIdyV43rdA7VJCzqzbEVlg8YDFhjY7e189AS0DExJ5szXj7jWpkz18IBHGod/nWYXqBKZgDIfKeKRaoCRHK32hzsfwZ3V+llmNdLbmai8CCvPS3wpZ2Hhs6vGeLrZMxVxKmY9RjOfaZzGr+TpCyHXFhanh3rN9rx0P+3fYFXVgr+Wbw9uVQoI48Xf6jiudDa6tJouQetWsOnqjHUQlkOqWScDFKMw0SPWlMO2mTiPurOwM6gYgMQx2bvG87TSUzGIYBkYdkv7YGHQ1efA9vbdSCdvMYTcMso7xuN/MIMAS80bx1fvLEaV10f9ABbN1AsLY/A1DJsZppzNMv2mkTEU0Dpa7detO7resCYf3g=}
provider:
  win: azure
bot:
  automerge: true
